<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 7.0.1 (Python 3.12.3 on win32)" generated="2024-12-06T16:05:33.671011" rpa="false" schemaversion="5">
<suite id="s1" name="31 TC 001 Get Request Robot" source="c:\Users\a315707\OneDrive - Deutsche Telekom AG\Schulungen\Programmierung\Python\PythonLearning\31_Start_API-Testing\31_TC_001_Get_Request_Robot.robot">
<test id="s1-t1" name="TC_001_Get_Request" line="9">
<kw name="Create Session" owner="RequestsLibrary">
<msg time="2024-12-06T16:05:34.691584" level="INFO">Creating Session using : alias=Get_Student_Details, url=https://thetestingworldapi.com/, headers={},                     cookies={}, auth=None, timeout=None, proxies=None, verify=False,                     debug=0 </msg>
<arg>Get_Student_Details</arg>
<arg>${Base_URL}</arg>
<doc>Create Session: create a HTTP session to a server</doc>
<status status="PASS" start="2024-12-06T16:05:34.690584" elapsed="0.004070"/>
</kw>
<kw name="GET On Session" owner="RequestsLibrary">
<msg time="2024-12-06T16:05:34.724165" level="WARN">Retrying (RetryAdapter(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("&lt;urllib3.connection.HTTPSConnection object at 0x000001A9EA1687D0&gt;: Failed to resolve 'thetestingworldapi.com' ([Errno 11001] getaddrinfo failed)")': /api/studentsDetails</msg>
<msg time="2024-12-06T16:05:34.947699" level="WARN">Retrying (RetryAdapter(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("&lt;urllib3.connection.HTTPSConnection object at 0x000001A9EA168B60&gt;: Failed to resolve 'thetestingworldapi.com' ([Errno 11001] getaddrinfo failed)")': /api/studentsDetails</msg>
<msg time="2024-12-06T16:05:35.369745" level="WARN">Retrying (RetryAdapter(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("&lt;urllib3.connection.HTTPSConnection object at 0x000001A9EA168F20&gt;: Failed to resolve 'thetestingworldapi.com' ([Errno 11001] getaddrinfo failed)")': /api/studentsDetails</msg>
<msg time="2024-12-06T16:05:35.391774" level="FAIL">ConnectionError: HTTPSConnectionPool(host='thetestingworldapi.com', port=443): Max retries exceeded with url: /api/studentsDetails (Caused by NameResolutionError("&lt;urllib3.connection.HTTPSConnection object at 0x000001A9EA169130&gt;: Failed to resolve 'thetestingworldapi.com' ([Errno 11001] getaddrinfo failed)"))</msg>
<var>${response}</var>
<arg>Get_Student_Details</arg>
<arg>/api/studentsDetails</arg>
<doc>Sends a GET request on a previously created HTTP Session.</doc>
<status status="FAIL" start="2024-12-06T16:05:34.695653" elapsed="0.703886">ConnectionError: HTTPSConnectionPool(host='thetestingworldapi.com', port=443): Max retries exceeded with url: /api/studentsDetails (Caused by NameResolutionError("&lt;urllib3.connection.HTTPSConnection object at 0x000001A9EA169130&gt;: Failed to resolve 'thetestingworldapi.com' ([Errno 11001] getaddrinfo failed)"))</status>
</kw>
<kw name="Log To Console" owner="BuiltIn">
<arg>${response}</arg>
<doc>Logs the given message to the console.</doc>
<status status="NOT RUN" start="2024-12-06T16:05:35.400987" elapsed="0.000000"/>
</kw>
<status status="FAIL" start="2024-12-06T16:05:34.689578" elapsed="0.711920">ConnectionError: HTTPSConnectionPool(host='thetestingworldapi.com', port=443): Max retries exceeded with url: /api/studentsDetails (Caused by NameResolutionError("&lt;urllib3.connection.HTTPSConnection object at 0x000001A9EA169130&gt;: Failed to resolve 'thetestingworldapi.com' ([Errno 11001] getaddrinfo failed)"))</status>
</test>
<status status="FAIL" start="2024-12-06T16:05:33.679905" elapsed="1.722602"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="31 TC 001 Get Request Robot">31 TC 001 Get Request Robot</stat>
</suite>
</statistics>
<errors>
<msg time="2024-12-06T16:05:34.724165" level="WARN">Retrying (RetryAdapter(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("&lt;urllib3.connection.HTTPSConnection object at 0x000001A9EA1687D0&gt;: Failed to resolve 'thetestingworldapi.com' ([Errno 11001] getaddrinfo failed)")': /api/studentsDetails</msg>
<msg time="2024-12-06T16:05:34.947699" level="WARN">Retrying (RetryAdapter(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("&lt;urllib3.connection.HTTPSConnection object at 0x000001A9EA168B60&gt;: Failed to resolve 'thetestingworldapi.com' ([Errno 11001] getaddrinfo failed)")': /api/studentsDetails</msg>
<msg time="2024-12-06T16:05:35.369745" level="WARN">Retrying (RetryAdapter(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("&lt;urllib3.connection.HTTPSConnection object at 0x000001A9EA168F20&gt;: Failed to resolve 'thetestingworldapi.com' ([Errno 11001] getaddrinfo failed)")': /api/studentsDetails</msg>
</errors>
</robot>
